### ISSUE TITLE
Display required Ruby version

### ISSUE THREAD

**Issue by budmc29** [ambethia/recaptcha#176]
It would be nice to display somewhere that the minimum required version is **>= 2.0**, and the last version that supports **ruby 1.9** is **0.4.0**.
That would save a few minutes for users than can't upgrade legacy applications.

**Comment by grosser** [comment]
I think bundler 1.12 will take care of that which should be released
shortly.
If I wanted to know when 1.9 was still supported I'd not go to the readme
but to rubygems and check the previous minor releases.
I know many apps that have this kind of ruby version requirement and none
of them document when the switch to 1.9/2.0 happened,
so I don't want to start it there since it will be only useful to very few
users and distraction for everyone else :(

**Comment by budmc29** [comment]
No worries then. You can close this issue.
