### ISSUE TITLE
README.md mentions verify_recaptcha_tags, which does not exist any more

### ISSUE THREAD

**Issue by maia** [ambethia/recaptcha#322]
The "Examples" section of README.md contains the following snippet:

````
  success = verify_recaptcha(action: 'login', minimum_score: 0.5)
  checkbox_success = verify_recaptcha_tags unless success
````

The master branch does not support #verify_recaptcha_tags – and it's unclear how this example code would need to be changed to run in v3.

**Comment by grosser** [comment]
@TylerRick got an idea how this was supposed to work ?

**Comment by grosser** [comment]
@maia the demo should have a working version, please check that and update here with what you find :)

**Comment by maia** [comment]
The demo (well, the parts which were recently updated) only use `#verify_recaptcha` – but the corresponding view also doesn't render a fallback v2 `recaptcha_tags`, as suggested in the example. In that case users with a score below a threshold will probably not be able to login at all.

**Comment by grosser** [comment]
:(
please update if you find out more

**Comment by maia** [comment]
I'm failing to find a way to search through old commits on github, somewhere along the way `#verify_recaptcha_tags` has probably been removed. 

@TylerRick can you identify what happened to the v2 fallback, and adjust the readme accordingly? Thanks.

**Comment by AdditionalTesting** [comment]
Any updates on this issue? What is the correct example for using on checkbox_success?
#verify_recaptcha_tags seems to not be available to me 
Attempting to use #verify_recaptcha (which is available) gives me 'ERROR for site owner: Invalid key type' in the reCaptcha checkbox, which is assume is because it is a v2 method. 
Any updates on what the correct v3 method is to proceed with checkbox_success??

**Comment by grosser** [comment]
@TylerRick seems to be missing, so please dig in the code to see how it's supposed to work :(

**Comment by nicholasshirley** [comment]
I can't figure out what this method was supposed to do, but it was introduced in the readme [for the v3 update](https://github.com/ambethia/recaptcha/commit/3ffacd491b844b18f1db440e1996902f16022acb#diff-04c6e90faac2675aa89e2176d2eec7d8R289). I don't see a method by that name anywhere else in the commit history.

**Comment by grosser** [comment]
Most likely forgotten during refactor ... Can you make a or to replace it
with the right method call ? (Or remove it if the right call is already
there)

**Comment by nicholasshirley** [comment]
I had some other problems with v3 so I haven't actually built a working v3 with v2 fallback, only the v2 version which is working as described in the readme.

I can try to build one, but a few questions if someone has already successfully built one with fallback:
* Do need to register separate keys for v3 and v2? It seems like this is the case since you have to specify which version you want to use when adding a new site (also would make sense why maia was not seeing the fallback in the demo site).
* If this strategy does require different keys, what would be the best way to implement the override? `secret_key` can be overriden in `verify_recaptcha` for both v3 and v2, but it looks like only `invisible_recaptcha_tags` will take an option to override `site_key`

The key question aside, I think the only change is to call `verify_recaptcha` instead of `verify_recaptcha_tags` (as the demo site does).

**Comment by TylerRick** [comment]
Taking a look...

**Comment by TylerRick** [comment]
Sorry about that. `verify_recaptcha_tags` never existed. That was a typo in the example. Fixed in #325.

As you discovered, the method to use in your controller — for both v2 and v3 — is [`verify_recaptcha`](https://github.com/ambethia/recaptcha#verify_recaptcha).

I also added a working example of a v2 fallback to the demo app, if you want to try it out. (Sorry, it's kind of ugly.)

Like you noticed, the biggest pain point for working with an app that uses both v2 and v3 is the fact that they require different keys and the fact that you can only configure the Recaptcha gem with one of them at a time.

I actually added the ability to configure with multiple keys (one for each of the 4 calls that require a different set of keys: `config.site_key_v2_checkbox =`, `config.site_key_v3 =`, ...) in my original PR, #310 (it also had some basic logging so you could actually see the error response from Google), but that PR was rejected and I no longer have the time or interest in submitting more PRs. If you are interested, I'm sure there would be an interest in a PR for that...

> * Do need to register separate keys for v3 and v2? 

Yes. You even need separate keys if using both invisible and checkbox, for example, in the same app. 

> * If this strategy does require different keys, what would be the best way to implement the override? `secret_key` can be overriden in `verify_recaptcha` for both v3 and v2, but it looks like only `invisible_recaptcha_tags` will take an option to override `site_key`

I wouldn't call it the _best_ way, but in the current released version, if you want to use both v2 and v3 calls in the same app, you have to manually pass in a matching set of keys to either the v2 calls or to the v3 keys (or both).

You pass `site_key` to the call that lives in the view/frontend (`recaptcha_tags` (to render the checkbox), `invisible_recaptcha_tags`, or `recaptcha_v3`) and pass `secret_key` to the `verify_recaptcha` call that lives in the controller/backend, making sure the  `secret_key` that you use corresponds to the `site_key` you passed to the frontend call that created the response token that you are verifying. Ugly, right?

**Comment by grosser** [comment]
Yeah pretty ugly ... got any more of these PRs ? :D

**Comment by AdditionalTesting** [comment]
Hey thanks for getting back to me. I ended up just using v2 invisible for
the time being. You are right, the main hurdle was trying to integrate v3
with the v2 fallback since they require a different set of keys. You're
suggestion sounds totally functional, if a bit ugly. I'll definitely give
it a try in the next release.
Thanks for the fix contribution.

Regards,
         - Albert
