### ISSUE TITLE
TypeError: Cannot set properties of null at setInputWithRecaptchaResponseTokenForConnectProvider

### ISSUE THREAD

**Issue by pritambios** [ambethia/recaptcha#424]
Rails version 7
Using with Turbo.

Error in browser console
```
VM366:11 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'value')
    at setInputWithRecaptchaResponseTokenForConnectProvider (<anonymous>:11:27)
    at <anonymous>:5:17
```
Code snippet where the issue is happening
```javascript
function executeRecaptchaForConnectProvider() {
            grecaptcha.ready(function() {
              grecaptcha.execute('<hidden site key>', {action: 'connect_provider'}).then(function(token) {
                setInputWithRecaptchaResponseTokenForConnectProvider('g-recaptcha-response-data-connect-provider', token)
              });
            });
          };
                    var setInputWithRecaptchaResponseTokenForConnectProvider = function(id, token) {
            var element = document.getElementById(id);
            element.value = token; // element is null
          }
```

**Comment by victor-fdez** [comment]
Hi @pritambios , I hope you're doing well. 

I wanted to reach out and let you know that I've submitted a pull request #425  that solves an issue with the `executeRecaptchaForConnectProvider` function. The issue was that sometimes the function would throw an error when it couldn't find an element by its ID, which would happen in our case when a user closed a modal which had `repatcha_v3` embedded in it and it couldn't find the hidden input tag.

The PR adds the optional `ignore_no_element: true` option to handle this issue. 

Hope this helps!

**Comment by grosser** [comment]
5.13.0 🎉
