### ISSUE TITLE
recaptcha in modal/overlay

### ISSUE THREAD

**Issue by aaron-m-h** [ambethia/recaptcha#55]
im having a problem getting the recaptcha script to generate in my modal/overlay partial.

the script im using is 
    <%= recaptcha_tags :display=>{:theme=>'white', :noscript => false}%>

<blah1> is what happens when i load in my overlay partial. end result is i cannot see the recaptcha

<blah> is what happens when i use the above script in a regular view.  and it displays properly.  

is there a work around for this?

here is the gist.

https://gist.github.com/ad2ff6371de4d6443f60

**Comment by AaronGaim** [comment]
Maybe it will help someone in the future.
Your problem is that Recaptcha gem loads the script inside the response which is text.
You probably do :

    .done (response, status) ->
	    $modal = $(response)
	    $modal.modal('show')

The only reason it does not work because of the string `<script>`, DOM layer can't parse what's js and what's HTML. When jquery creates DOM elements from the response, your Recaptcha js just not fire.

	.done (response, status) ->
		$modal = $(response)
		$scripts = $modal.find('script').remove().clone() # Find the scripts , copy and remove old.
		$modal.modal('show')
		$modal.on 'shown.bs.modal', ()->
			$scripts.appendTo( $modal )

		# Other solution - you probably can append it to head, body, etc. 
		# But it the script will exist even after modal destroyed
		# $modal = $(response)
		# $modal.modal('show')
		# $(document.body).append $modal.find('script')

So you just remove the js this and bring it back, hope it helps.
